### ISSUE TITLE
Vidio Auto stop

### ISSUE THREAD

**Issue by Achu2234** [pytgcalls/pytgcalls#101]
When i am playing yt live or vidio after some min vidio is stoping  auto anyway to fix it

**Comment by Megumin2167** [comment]
same in my also

**Comment by Laky-64** [comment]
Hi @Achu2234, what version of PyTgCalls are you using?

**Comment by Achu2234** [comment]
@Laky-64 sir using 8.0

**Comment by Laky-64** [comment]
Ahh, is a know issue, btw we have fixed on the 0.8.1 beta version

**Comment by Achu2234** [comment]
ok sir
