### ISSUE TITLE
JoinGroupCall with create option

### ISSUE THREAD

**Issue by killteamseller** [pytgcalls/pytgcalls#115]
Can you add method for create (start) new voice chat?
can you add change title of voice chat? + update if an admin change the title
can you optimize consume of cpu and ram on linux?

**Comment by Laky-64** [comment]
Added in PyTgCalls 1.1.0b1

**Commit**
https://github.com/pytgcalls/pytgcalls/commit/fa4ae2ff010ed48da60c77ecdd69e9007cdd4e56

**PyPi**
https://pypi.org/project/py-tgcalls/1.1.0b1/
