### ISSUE TITLE
ERROR:root:joinCallError -> Error: No active voice chat found on XXXXX

### ISSUE THREAD

**Issue by ChenMoGe2** [pytgcalls/pytgcalls#125]
**Describe the bug**
Hi,I have a problem when I using pytgcalls.I start main function from example/multiple_calls/example_multiple.py.And I can login 2 client successfully and I start video group call at group chat.But when I send message(!p1 or !p2) to group chat,the pytgcalls example printf error message
ERROR:root:JOIN_VOICE_CALL_ERROR -> init() got an unexpected keyword argument 'video_stopped'
ERROR:root:joinCallError -> Error: No active voice chat found on XXXXX
I don't know hot to solve this and who can help me.Thank you.

**To Reproduce**
1. Go to 'start example/multiple_calls/example_multiple.py by python example_multiple.py'
2. Click on 'phone number to login account A and B'
3. Using telegram app which is account A to create a group call in a group chat which A and B are all in the group chat
4. Send message !p2 to start join group call request
5. The error messages are printf at console

**Expected behavior**
Can recevie input.raw on account A in group call

**Log**
ERROR:root:JOIN_VOICE_CALL_ERROR -> init() got an unexpected keyword argument 'video_stopped'
ERROR:root:joinCallError -> Error: No active voice chat found on XXXXX

**Window (please complete the following information):**
 - OS: [e.g. Window 10]
 - NodeJS Version [e.g. v16.13.0]
 - Python Version [e.g. 3.8.5]

**Comment by Laky-64** [comment]
Hi, what PyTgCalls version are you using?

**Comment by ChenMoGe2** [comment]
@Laky-64 master branch,using pip version 1.2.9

**Comment by Laky-64** [comment]
Ok, then, i mean PyTgCalls version, not the Pyrogram Version

**Comment by ChenMoGe2** [comment]
0.8.0

**Comment by Laky-64** [comment]
Ok, then i suggest to you to switch to the newer PyTgCalls version, (Beta Version 0.8.1)

**Comment by ChenMoGe2** [comment]
OK,thanks.I will try it
