### ISSUE TITLE
In some cases there are freezes.

### ISSUE THREAD

**Issue by sobotlar** [pytgcalls/pytgcalls#131]
In some cases there are freezes. The server is very powerful. But in some cases, videos or music continue to freeze. how did i fix it?

**Comment by Laky-64** [comment]
Can you send here logs in debug mode only for pytgcalls?

**Comment by sobotlar** [comment]
> Can you send here logs in debug mode only for pytgcalls?
                    try:
                        await pytgcalls.change_stream(
                                chatid,
                                AudioVideoPiped(video_data),
                            )
                    except:
                        await pytgcalls.join_group_call(
                                chatid,
                                AudioVideoPiped(video_data)
                            )

**Comment by Laky-64** [comment]
Logs, not the source code

**Comment by sobotlar** [comment]
> Logs, not the source code

Send an example

**Comment by Laky-64** [comment]
Do you what is it logs?

https://en.wikipedia.org/wiki/Logging_(software)

**Comment by sobotlar** [comment]
> Do you what is it logs?
> 
> https://en.wikipedia.org/wiki/Logging_(software)

There is no Error. I looked at the logs. No bot works without problems. But there are some delays when reading assistant. Freezes

**Comment by Laky-64** [comment]
i need logs in debug mode

**Comment by sobotlar** [comment]
> i need logs in debug mode


Debug Mode is not on unfortunately

@MusicDepoRu Go here and you can see the issue right now.

**Comment by Laky-64** [comment]
Turn on and then send to me the logs

**Comment by Laky-64** [comment]
Btw try to check your server cpu usage and your bandwidth

**Comment by sobotlar** [comment]
> Btw try to check your server cpu usage and your bandwidth

I see it's normal now. Are there any differences between .raw or .mp3 while reading?

**Comment by Laky-64** [comment]
Yes, is different, read:

https://pytgcalls.github.io/
