### ISSUE TITLE
Add possibility to record a Group Call

### ISSUE THREAD

**Issue by Xun66** [pytgcalls/pytgcalls#134]
Is it possible to support fifo for receiving audio?

I try to connect telegram audio call with my talkie walkie, so I need two-way audio fifo.

**Comment by Xun66** [comment]
> wdym?

I am trying to connect my telephone to Telegram to make/answer phone calls with Telegram. I need an input FIFO buffer and an output FIFO buffer to get real-time audio chat instead of playing sound from a media file and recording sound to a media file.

Pytgcalls has output FIFO, but is it possible to support input FIFO buffer so I can receive audio from the chat room in real-time?

**Comment by Laky-64** [comment]
Mhh, needed to be studied an implementation about recording group call

**Comment by Xun66** [comment]
The [example_mic](https://github.com/pytgcalls/pytgcalls/blob/0f29e200c6d1517cb3109783161aa5a7c1aa9e7d/example/capture_mic/example_mic.py) from update 0.9.0 has demonstrated what I need! To get a real-time audio stream, I can set the input to an InputAudioStream.

Thanks for your work!
