### ISSUE TITLE
Add VoIP::isPlaying()

### ISSUE THREAD

**Issue by afeno** [pytgcalls/pytgcalls#141]
**Is your feature request related to a problem?**
I would like to finish the outbound call (calls started by pytgcalls) when the play is over.

**Describe the solution you'd like**
I would like to have the isPlaying method added into pytgcalls. Some libraries based on libtgvoip are having it.

**Describe alternatives you've considered**
I couldn't find any alternative. I finishing the call after a manual timeout but I can't check if the audio file is still being played.

**Additional context**
I can pay for the implementation of it.

**Comment by tappo03** [comment]
Use on_stream_end decorator

[on_stream_end](https://pytgcalls.github.io/api/decorators.html#pytgcalls.PyTgCalls.on_stream_end)

**Comment by Laky-64** [comment]
Already exist:

https://pytgcalls.github.io/api/methods/get_active_call.html

**Comment by Laky-64** [comment]
I think this issue now is fixed, then i will close it
