### ISSUE TITLE
'PyTgCalls' from 'pytgcalls'

### ISSUE THREAD

**Issue by kthenurseone** [pytgcalls/pytgcalls#142]
Traceback (most recent call last):
  File "join_vc.py", line 7, in <module>
    from pytgcalls import PyTgCalls
ImportError: cannot import name 'PyTgCalls' from 'pytgcalls' (C:\Users\Kerim\AppData\Local\Temp\_MEI1875682\pytgcalls\__init__.pyc)

What is the way to solve this problem ? It runs on my computer but when I carry it to another it doesn't work :/

Here is my  file:

import os
import time
import pyrogram
import pytgcalls

from pyrogram import Client
from pytgcalls import PyTgCalls
from pytgcalls import StreamType
from pytgcalls.types.input_stream import InputAudioStream
from pytgcalls.types.input_stream import InputStream

import argparse

parser = argparse.ArgumentParser(description='A test program.')
parser.add_argument('-session', '--session', help='Session')
parser.add_argument('-api_id', '--api_id', help='api_id')
parser.add_argument('-api_pass', '--api_pass', help='api_pass')
parser.add_argument('-chat', '--chat', help='chat')
args = parser.parse_args()
app = Client(
    str(args.session),
    api_id=int(args.api_id),
    api_hash=str(args.api_pass)
)

print(args.session)
call_py = PyTgCalls(app)
call_py.start()
# app.join_chat(str(args.chat))
chat = app.get_chat(args.chat)
# print(chat["id"])
file = 'input.raw'
while not os.path.exists(file):
    time.sleep(0.125)
call_py.join_group_call(
    int(chat["id"]),
    InputStream(
        InputAudioStream(
            file,
        ),
    ),
    stream_type=StreamType().local_stream,
)
from pytgcalls import idle
idle()

**Comment by kthenurseone** [comment]
![image](https://user-images.githubusercontent.com/54042275/154791988-f28d78f6-9844-4b6d-bdfc-c5f434cf9eca.png)

**Comment by doggyhaha** [comment]
Did you install py-tgcalls or pytgcalls? The right name to install is py-tgcalls

**Comment by doggyhaha** [comment]
> ![image](https://user-images.githubusercontent.com/54042275/154791988-f28d78f6-9844-4b6d-bdfc-c5f434cf9eca.png)

Try uninstalling pytgcalls if installed and install only py-tgcalls, and then recompile the script

**Comment by kthenurseone** [comment]
Hi, how can I call it then ? 
import pytgcalls or import py-tgcalls ?

**Comment by doggyhaha** [comment]
> Hi, how can I call it then ?
> import pytgcalls or import py-tgcalls ?

You install py-tgcalls but import “pytgcalls”, so your code is right, I didn’t notice anything wrong, just install the right lib and recompile

**Comment by kthenurseone** [comment]
I did what you said. It's still running as a python script but when I compile it with pyinstaller

   File "join_vc.py", line 8, in <module>
    from pytgcalls import PyTgCalls
ImportError: cannot import name 'PyTgCalls' from 'pytgcalls' (C:\Users\Kerim\AppData\Local\Temp\_MEI95602\pytgcalls\__init__.pyc)


Same error happens :/

**Comment by doggyhaha** [comment]
> I did what you said. It's still running as a python script but when I compile it with pyinstaller
> 
> File "join_vc.py", line 8, in from pytgcalls import PyTgCalls ImportError: cannot import name 'PyTgCalls' from 'pytgcalls' (C:\Users\Kerim\AppData\Local\Temp_MEI95602\pytgcalls__init__.pyc)
> 
> Same error happens :/

If it works as a Python script it’s probably a PyInstaller problem, i can’t try right not but check this answer https://stackoverflow.com/questions/22104506/pyinstaller-failing-to-include-some-modules-from-c-python27-lib

**Comment by Laky-64** [comment]
This issue is resolved?
