### ISSUE TITLE
Add a way for streaming in live from a webcam

### ISSUE THREAD

**Issue by lucabinotti** [pytgcalls/pytgcalls#143]
**Is your feature request related to a problem? Please describe.**
From the API there are no way for streaming in live from a webcam

**Describe the solution you'd like**
A method for streaming from a webcam, maybe with the option of choosing from which webcam (in case there are more webcams connected)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by killteamseller** [comment]
Workaround:
you can do a YT live (private) and stream it.

**Comment by lucabinotti** [comment]
@killteamseller it is not the same since there is latency in YT lives and since live would be always on. btw thanks for the advice.

**Comment by Laky-64** [comment]
The real problem is currently there aren't ffmpeg api to for Linux, windows have dshow

If you know an ffmpeg api for Linux users, tell me

**Comment by Laky-64** [comment]
But isn't a system level library right? Is a third party lib

**Comment by lucabinotti** [comment]
@Laky-64 if I'm not wrong it is a third-party library, but I guess that it is the only option

**Comment by Laky-64** [comment]
> @Laky-64 if I'm not wrong it is a third-party library, but I guess that it is the only option

Needed a solution at system level

**Comment by zzvvmm** [comment]
> Now is possible to do using a simple local udp stream

Thank you but can you explain the solution? How do you use local Udp stream and pytgcalls together?
