### ISSUE TITLE
Can't install py-tgcalls

### ISSUE THREAD

**Issue by sans404-dev** [pytgcalls/pytgcalls#147]
**Describe the bug**
Repositories return a 404 error

**To Reproduce**
1. python3.10 -m pip install git+https://github.com/pytgcalls/pytgcalls -U
2. ERROR https://pastebin.com/hEYXQ15a
**Expected behavior**
Successful installation

**Log**
Error log pip with verbosity 3 https://pastebin.com/BrMWGQ1a

**Linux (please complete the following information):**
 - OS: [Android 10 (termux)]
 - NodeJS Version [17.8.0]
 - Python Version [3.10.4]

**Additional context**
node-pre-gyp ERR! install response status 404 Not Found on https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/android-arm64.tar.gz
      node-pre-gyp ERR! install error
      node-pre-gyp ERR! stack Error: response status 404 Not Found on https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/android-arm64.tar.gz

**Comment by json1c** [comment]
+

**Comment by json1c** [comment]
similar problem

**Comment by Laky-64** [comment]
Just use ubuntu termux, don't use other os
