### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by json1c** [pytgcalls/pytgcalls#148]
**Describe the bug**
clients do not enter the chat and do not play music, they throw an exception

**To Reproduce**
use youtube-dl and multiaccount

**Expected behavior**
clients entering voice chat and playing music

**Log**
https://pastebin.com/S3Fna1PQ

**Linux (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - NodeJS Version [e.g. 17.8.0]
 - Python Version [e.g. 3.10]

**Additional context**
code: https://github.com/json1c/telegram-raid-botnet/blob/master/functions/archive/voice_chat.py

**Comment by Laky-64** [comment]
This happens because you're mixing Async with Sync

**Comment by json1c** [comment]
where is this happening?

**Comment by Laky-64** [comment]
Not PyTgCalls problem
