### ISSUE TITLE
Option for additional_ffmpeg_parameter right after -i <video link>

### ISSUE THREAD

**Issue by billa298** [pytgcalls/pytgcalls#149]
**Is your feature request related to a problem? Please describe.**
My video file has multiple audio tracks. If I wanna play say 2nd audio track, The ffmpeg command should be: ffmpeg -i <video_link> -map 0: a :1 <other parameters here> but there is no option to add parameters rights after input. (if i use -map at the very end using 'atend', its ignored by ffmpeg.)

**Describe the solution you'd like**
The additional_ffmpeg_parameters should be in this format: "<parameters before -i> -atmid <parameters after -i> -atend <parameters at the very end>"

**Describe alternatives you've considered**

**Additional context**

**Comment by Laky-64** [comment]
You want the atmiddle in what format?

You want this format?
`<parameters before -i> -i PATH -atmid <parameters after -i> -atend <parameters after all>`

**Comment by billa298** [comment]
Yes exactly

**Comment by Laky-64** [comment]
Was added with the 0.9.0

**Comment by billa298** [comment]
Hey but now that would create another issue(sorry i didn't noticed this before). If i now use map parameter and select an audio stream, the same parameter would be applied for  'raw video ffmpeg command'. But that would output error since we wouldn't have any input video stream selected.


Which means we need to have an option to add those parameters separately for raw audio and raw video commands. 

Something like:
additional_ffmpeg_parameter_video="",
additional_ffmpeg_parameter_audio=""

**Comment by Laky-64** [comment]
Already added also this, but command side:

https://github.com/pytgcalls/pytgcalls/blob/master/example/additional_ffmpeg_parameters/additional_ffmpeg_parameters.py#L26

**Comment by billa298** [comment]
Awesome! Can't thank you enough :)
