### ISSUE TITLE
Add support for architecture s390x

### ISSUE THREAD

**Issue by notudope** [pytgcalls/pytgcalls#151]
I need this library to support the linux-s390x architecture.

**Comment by Laky-64** [comment]
I don't know if exist the availability of build for s390x, but you can check how PyTgCalls are automatically built:

Github Action
https://github.com/pytgcalls/pytgcalls/blob/master/.github/workflows/build-and-publish-wheels.yml

The Docker File
https://github.com/pytgcalls/pytgcalls/blob/master/platforms/linux/Dockerfile

If you know if is supported, make test by your self then send a PR

Thank You in advance❤️

**Comment by notudope** [comment]
> I don't know if exist the availability of build for s390x, but you can check how PyTgCalls are automatically built:
> 
> Github Action https://github.com/pytgcalls/pytgcalls/blob/master/.github/workflows/build-and-publish-wheels.yml
> 
> The Docker File https://github.com/pytgcalls/pytgcalls/blob/master/platforms/linux/Dockerfile
> 
> If you know if is supported, make test by your self then send a PR
> 
> Thank You in advance❤️

There is no support for s390x in this repo.  I tried to fork, edit the action and include s390x but failed because official node-webrtc library doesn't support s390x architecture :(

**Comment by notudope** [comment]
When I try to build the node-webrtc library manually it stopped because found an error:
```
...
[  9%] Performing download step for 'project_libwebrtc'                                                                             export PATH=$DEPOT_TOOLS:$PATH                                                          gclient config --unmanaged --spec 'solutions=[{"name":"src","url":"https://webrtc.googlesource.com/src.git"}]'                      Errors:                                       failed to resolve infra/3pp/tools/git/linux-s390x@version:2@2.35.1.chromium.8 (line 27): no such package: infra/3pp/tools/git/linux-s390x
...
```

**Comment by Laky-64** [comment]
if webrtc doesn't support s390x currently we can't do anything

**Comment by notudope** [comment]
> if webrtc doesn't support s390x currently we can't do anything

Yes, I know. But I found this one https://github.com/node-webrtc/node-webrtc/issues/721#issuecomment-1078198487.

I hope he can make it support for s360x.
