### ISSUE TITLE
Facing Some Server problems 

### ISSUE THREAD

**Issue by ITZ-ZAID** [pytgcalls/pytgcalls#154]
Client booted successfully No any bug there but Still when j tryied to play its was saying
ERROR: pytgcalls:Telegram Server is having some internal problems

Some server r not support maybe 
I have United States, Lincoln, NE server

**Linux (please complete the following information):**
 - OS: [Linux]
 - NodeJS Version [16]
 - Python Version [. 3.8.9]

Pls try to fix

**Comment by ITZ-ZAID** [comment]
I tried both PyroGram and telethon

**Comment by Laky-64** [comment]
Needed a little reproducible code...

**Comment by Laky-64** [comment]
if the problem is Provider side, use another provider 😅, the problem can be your provider not allow wrtc connections

**Comment by ITZ-ZAID** [comment]
Yeah, sure by the by thanks for your response.

**Comment by Laky-64** [comment]
You're welcome
