### ISSUE TITLE
crypto_1.getRandomValues is not a function in utils.js

### ISSUE THREAD

**Issue by simony666** [pytgcalls/pytgcalls#163]
**Describe the bug**
Error show TypeError: (0 , crypto_1.getRandomValues) is not a function in 
pytgcalls\dist\utils.js:7

**To Reproduce**
1. Run the code (given in pastebin below)
2. See error

**Code**
https://pastebin.com/PekQFG4L

**Log**
https://pastebin.com/cB8JuNax

**Linux (please complete the following information):**
 - OS: [e.g.Window 11]
 - NodeJS Version [16.17.0]
 - Python Version [ 3.10.5 ]

**Comment by Laky-64** [comment]
Fixed with 0.9.3, i will close this issue as solved
