### ISSUE TITLE
ZeroDivisionError when streaming videos with Cover Art

### ISSUE THREAD

**Issue by odysseusmax** [pytgcalls/pytgcalls#164]
**Describe the bug**
When trying to stream a video that has cover art, the below error is getting raised.
```
Traceback (most recent call last):
  File "d:\projects\tgcall\bot.py", line 81, in start
    await call_py.join_group_call(
  File "D:\projects\tgcall\venv\lib\site-packages\pytgcalls\methods\groups\join_group_call.py", line 196, in join_group_call
    await stream.check_pipe()
  File "D:\projects\tgcall\venv\lib\site-packages\pytgcalls\types\input_stream\audio_video_piped.py", line 82, in check_pipe
    width, height = check_video_params(
  File "D:\projects\tgcall\venv\lib\site-packages\pytgcalls\types\input_stream\video_tools.py", line 47, in check_video_params
    width, height = resize_ratio(dest_width, dest_height, 100)
  File "D:\projects\tgcall\venv\lib\site-packages\pytgcalls\types\input_stream\video_tools.py", line 32, in resize_ratio
    rescaling = ((720 if h > 720 else h) * 100) / h
ZeroDivisionError: division by zero
```

**To Reproduce**
1. An example file can be found [here](https://t.me/b23rxcertj28hj4)
2. Download the file and pass it to `join_group_call` method. 
```
call_py.join_group_call(
    m.chat.id,
    AudioVideoPiped(remote_url, HighQualityAudio(), HighQualityVideo()),
    stream_type=StreamType().pulse_stream,
)
```

**Log**
Media info for this particular file: <https://nekobin.com/qemelurulo>

**Windows 10:**
 - NodeJS Version v16.17.0
 - Python Version 3.10.4

**Additional context**
My guess is that, because this file has 2 `video` streams (actual video stream and the cover art, check the attached media info) in [`FFprobe.check_file`](https://github.com/pytgcalls/pytgcalls/blob/95b6c59c0aca47c4d46725ce7302c663ad607fa2/pytgcalls/ffprobe.py#L79), inside the for loop, [this](https://github.com/pytgcalls/pytgcalls/blob/95b6c59c0aca47c4d46725ce7302c663ad607fa2/pytgcalls/ffprobe.py#L84) condition is true for the cover art stream, which is overwriting the actual video's width and height to 0. Maybe adding `mjpeg` to the `image_codecs` list will solve this issue, not sure whether it will have any other impact.

**Comment by Laky-64** [comment]
What's your PyTgCalls version?

**Comment by odysseusmax** [comment]
> What's your PyTgCalls version?

0.9.3

**Comment by Laky-64** [comment]
Can you try to fix it with a pull request?
