### ISSUE TITLE
Update the code

### ISSUE THREAD

**Issue by PREETCHAUHAN** [pytgcalls/pytgcalls#166]
in check_environment
    raise TooOldNodeJSVersion(
pytgcalls.exceptions.TooOldNodeJSVersion: Needed node 15.0.0+, actually installed is 10.19.0

INFO:pytgcalls:Node.js stopped
INFO:pytgcalls:Node.js stopped
INFO:pytgcalls:Node.js stopped
INFO:pytgcalls:Node.js stopped
INFO:pytgcalls:Node.js stopped
 - OS: [e.g. Linux Mint 20.1]
 - NodeJS Version [e.g. 1.14]
 - Python Version [e.g. 3.8.6]

**Additional context**

**Comment by doggyhaha** [comment]
Read the error, you need nodejs 15.0.0 or higher
