### ISSUE TITLE
app.get_active_call(chat_id) not returning active call from the group

### ISSUE THREAD

**Issue by Muhammad-Aadil** [pytgcalls/pytgcalls#167]
I have tried this method with the group where the call is active and the user is a part of that call but not getting the correct response back, instead always getting an error.

Group call not found with the chat id -100123123123

I have also searched for this in the Official Telegram Group, Some people have faced this problem before but No solution was provided there.

**Comment by Laky-64** [comment]
Read the following documentation, there is a valid reason

https://pytgcalls.github.io/api/methods/get_active_call.html

**Comment by Muhammad-Aadil** [comment]
I am sorry If I missed something from the documentation. 
As I have stated above, when there is an active call in the group, this method should return that call, instead, I am always getting the response "Group call not found". 


yes, I have read the instruction before which says it will raise an error if there is no active call.
but I am saying there is an active call and the method is raising an error.

**Comment by Laky-64** [comment]
This method is not used to know if there is an active call in the group, it is used to know if you are playing something in that particular group

**Comment by Muhammad-Aadil** [comment]
Okay, I am really sorry and Thanks for your time :)

**Comment by Muhammad-Aadil** [comment]
@Laky-64 I want to check the active/scheduled call in the group, can you please tell me how to do that? Thanks :)

**Comment by Laky-64** [comment]
That's sounds more like a Pyrogram/Telethon question
