### ISSUE TITLE
join_group_call without playing anything

### ISSUE THREAD

**Issue by rainrisa** [pytgcalls/pytgcalls#175]
**Is your feature request related to a problem? Please describe.**
I want to join vidcall without playing anything, and just listen to other person when they talk

**Describe the solution you'd like**
Seems like join_group_call really needs a `stream` parameter, can we just set it to `None` ?https://github.com/pytgcalls/pytgcalls/blob/4e697ef4d9842ab88c0362eac278538e61ee134c/pytgcalls/methods/groups/join_group_call.py#L37-L44

**Comment by TuriOG** [comment]
It is now possible if you upgrade to the current latest version (1.0.2).
