### ISSUE TITLE
Stuttering if telegram client is running with the script.

### ISSUE THREAD

**Issue by xlyofc** [pytgcalls/pytgcalls#179]
**Describe the bug**
When you run the code from the same machine that have an telegram client (windows desktop) running, it will make the streamed audio/video "stutter" randomly, and i'm sure that it is not low memory, high cpu usage, i have an Ryzen 5 5600G with 16gb DDR4 3200mHz

**To Reproduce**
1. Open an telegram client for desktop on the machine that will run the code.
2. Try run an call streaming (video or audio, any quality).
3. See error : you gonna see the behavior.

**Expected behavior**
Will randomly have some stuttering on the video/audio, and changing quality does not solve a single thing.

**Linux (please complete the following information):**
 - OS: [Windows 11 (most recent)]
 - NodeJS Version [Most Recent]
 - Python Version [Most Recent]

**Comment by Laky-64** [comment]
Surely it will be the stream source's fault, but I would advise you to enable verbose logging anyway

At the same time I would tell you to try turning off the lip sync if you are streaming a video with audio

**Comment by SmartManoj** [comment]
https://nekobin.com/wetedegani
why is there is a pause at the end?
---
https://nekobin.com/xoroxujuqe
Is this part of log enough?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/234313518-16992909-a266-491f-ad3a-f5f48488960c.png)

**Comment by Laky-64** [comment]
Can you show me your code with the high level methods?

**Comment by SmartManoj** [comment]
Used this https://github.com/pytgcalls/pytgcalls/blob/master/example/piped_audio_calls/example_piped_audio.py

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/234321511-7d789ea3-98ab-4872-a6d5-55045f2d9be5.png)

**Comment by Laky-64** [comment]
Oh, i didn't read the first message of this conversation, sorry, it's a known strange issue of TDesk maybe? Happens only with tgdesktop

**Comment by Laky-64** [comment]
Try on Linux machine, a real Linux machine, not like WSL, and not with a VM

**Comment by SmartManoj** [comment]
Tested in Manjaro. Works fine but there is slight voice low at the end.

**Comment by Laky-64** [comment]
The problem is just Windows related
