### ISSUE TITLE
userbot is just joining and leaving.

### ISSUE THREAD

**Issue by annihilatorrrr** [pytgcalls/pytgcalls#198]
**Describe the bug**
The player (userbot) is joining the video call and leaving it without streaming/ playing anything, this bug came after the release of pytgcalls- 1.1.1.
Everything was **just ok** until 1.1.0.

**To Reproduce**
Just play any yt downloaded audio file.

**Expected behavior**
Should be playing the audio file.

**Log**
N/A

**Linux (please complete the following information):**
 - OS: bookworm-slim
 - Python Version 3.12.1

**Additional context**
ig the latest ffmpeg command is a mess ?

**Comment by Laky-64** [comment]
Can you show me your code?

**Comment by KSKOP69** [comment]
> Can you show me your code?

`github.com/Pranav-Saraswat/Testing-Alpha`

**Comment by annihilatorrrr** [comment]
> Can you show me your code?

https://github.com/Pranav-Saraswat/Testing-Alpha1

**Comment by annihilatorrrr** [comment]
> > Can you show me your code?
> 
> `github.com/Pranav-Saraswat/Testing-Alpha`

bruh

**Comment by KSKOP69** [comment]
> > > Can you show me your code?
> > 
> > 
> > `github.com/Pranav-Saraswat/Testing-Alpha`
> 
> bruh

yukki kang 🤡

**Comment by Pranav-Saraswat** [comment]
@KSKOP69 lol

**Comment by Laky-64** [comment]
Fixed starting from py-tgcalls 1.1.2, b94ced4026bdbf24a0e3b5f6b3a5968aadc8f83d
