### ISSUE TITLE
RTSP Streaming

### ISSUE THREAD

**Issue by undermuz** [pytgcalls/pytgcalls#203]
rtsp url is not working

```
call_py = PyTgCalls(app)
call_py.start()

video_file = "rtsp://admin:1234@192.168.1.196:554/ISAPI/Streaming/Channels/101"
# video_file = "http://docs.evostream.com/sample_content/assets/sintel1m720p.mp4"

call_py.join_group_call(
    -1234,
    MediaStream(video_file),
)

idle()
```

**Comment by Laky-64** [comment]
Are you getting any error?

**Comment by Laky-64** [comment]
Do you have any rtsp test stream?

**Comment by undermuz** [comment]
@Laky-64 
No, i dont, but I'll try to figure out how to reproduce it

**Comment by undermuz** [comment]
@Laky-64 
create `rtsp-simple-server.yml`:

```
protocols: [TCP]
paths:
  all:
    source: publisher
```

`docker run --rm -it -v $PWD/rtsp-simple-server.yml:/rtsp-simple-server.yml -p 8554:8554 aler9/rtsp-simple-server:v1.3.0` - start server
`ffmpeg -re -stream_loop -1 -i test.mp4 -f rtsp -rtsp_transport tcp rtsp://localhost:8554/live.stream` - start stream
`ffprobe -rtsp_transport tcp -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 2 -v error -show_entries stream=width,height,codec_type,codec_name -of json -i rtsp://localhost:8554/live.stream` - get info about stream
`ffmpeg -rtsp_transport tcp -i "rtsp://localhost:8554/live.stream" ./test2.mp4` - test record stream, press q after ~10 seconds

Run python code
```
...

video_file = "rtsp://localhost:8554/live.stream"

call_py.join_group_call(
    <YOUR CHAT ID>,
    MediaStream(video_file, additional_ffmpeg_parameters="-rtsp_transport tcp"),
)

...
```

**Comment by Laky-64** [comment]
Can you try with this version if was fixed it?
https://pypi.org/project/py-tgcalls/1.2.0b3/

**Comment by undermuz** [comment]
@Laky-64 
Yes, it works! Thanks! 🎉🎉

**Comment by Laky-64** [comment]
Fixed
