### ISSUE TITLE
Sir please fix this error

### ISSUE THREAD

**Issue by jattpawan** [pytgcalls/pytgcalls#21]
ImportError: cannot import name 'EditGroupCallParticipant' from 'pyrogram.raw.functions.phone' (/usr/local/lib/python3.9/site-packages/pyrogram/raw/functions/phone/__init__.py)

**Comment by BlackStoneReborn** [comment]
Stop asking things like this, it's definitely a idden issue which you can fix with ease:
pip3 install -U git+https://github.com/pyrogram/pyrogram.git

Done 😄

**Comment by jattpawan** [comment]
Sir but i am not pyrogram user
Check out my repo
https://github.com/jattpawan/evilbot
