### ISSUE TITLE
nodejs

### ISSUE THREAD

**Issue by Ling-ex** [pytgcalls/pytgcalls#218]
I want to ask about connecting to nodejs, I have installed nodejs but nodejs is not connecting..... why is that?

please answer. Thank You

**Comment by doggyhaha** [comment]
@Ling-ex Ma come cazzo scrive sta gente

**Comment by Ling-ex** [comment]
> @Ling-ex Why do you want to connect with node js ?

as a function I can't use it if it's not connected to nodejd :(

**Comment by Ling-ex** [comment]
> Why are you still using NodeJS version instead of latest versions like 1.2.7?
> 
> Btw can you share the code?

Of course.

@Client.on_message(filters.command("play"))
async def playing(c: Client, m: types.Message):
    if m.reply_to_message:
        if len(m.command) < 2:
            chat_id = m.chat.id
        else:
            chat_id = int(m.text.split()[1])
        if m.reply_to_message.audio or m.reply_to_message.voice:
            _play_ = await m.reply_to_message.reply_msg("<b>Processing Audio...</b>")
            dl = await m.reply_to_message.download()
            link = m.reply_to_message.link
            if chat_id in music.call_py._call_holder._calls:
                pos = await queues.put(chat_id, file=AudioPiped(dl, HighQualityAudio()))
                await _play_.delete_msg()
                await m.reply_to_message.reply_msg(
                    f"<b>💡 <a href={link}>Audio</a> Queues » {pos}</b>",
                    disable_web_page_preview=True,
                    del_in=60
                )
            else:
                await music.call_py.join_group_call(
                    chat_id,
                    AudioPiped(dl, HighQualityAudio()),
                    stream_type=StreamType().pulse_stream,
                )
                await _play_.delete_msg()
                await m.reply_to_message.reply_msg(
                    f"<b>▶️ Twisted <a href={link}>Audio</a></b>",
                    disable_web_page_preview=True,
                    del_in=60
                )

I have used the latest version of PyTgCalls 1.2.7

**Comment by bcncalling** [comment]
@Ling-ex Share your code using nekobin.com else batbin.me 🚶‍♂
