### ISSUE TITLE
Can't install for "Failed building wheel for ntgcalls"

### ISSUE THREAD

**Issue by kinkyitaly** [pytgcalls/pytgcalls#219]
Hi there. I'm using a Raspberry pi 4 (8 GB Ram) running ArchLinux (ARM-rpi-armv7 version). 

I installed/uploaded everything needed (pip version is 24.0 and python version is 3.11.7).

Everytime I try to install PyTgCalls (I tried "pip3 install -U py-tgcalls" and also "pip3 install -U git+https://github.com/pytgcalls/pytgcalls") I get the same error:

<img width="1106" alt="Screenshot 2024-02-23 alle 00 12 08" src="https://github.com/pytgcalls/pytgcalls/assets/140807890/4a0c9f2c-5e5e-4e70-9e54-b5ea8d1752a7">

Can someone please help me? Thank you very much

**Comment by Laky-64** [comment]
NTgCalls isn't available on armv7 devices, since they are out of support

**Comment by kinkyitaly** [comment]
> NTgCalls isn't available on armv7 devices, since they are out of support

Oh I understand. So should I be able to install it if I pass to ArchLinuxARM-rpi-aarch64 version?

**Comment by Laky-64** [comment]
Yes

**Comment by kinkyitaly** [comment]
> Yes

Thank you so much for the fast and kind reply to a noob like me :)

**Comment by Laky-64** [comment]
Don't worry, then I can close this issue, for any other further problem, feel free to ask
