### ISSUE TITLE
ImportError: cannot import name 'EditGroupCallParticipant' from 'pyrogram.raw.functions.phone' (/usr/local/lib/python3.9/site-packages/pyrogram/raw/functions/phone/__init__.py)

### ISSUE THREAD

**Issue by jattpawan** [pytgcalls/pytgcalls#22]
Sir please fix this issue

**Comment by rojserbest** [comment]
This issue is [duplicate](https://github.com/pytgcalls/pytgcalls/issues/20).

Just upgrade Pyrogram with:
```bash
    pip(3) install --upgrade http://github.com/pyrogram/pyrogram
```

And close this issue.

**Comment by Laky-64** [comment]
Duplicated issue

**Comment by jattpawan** [comment]
Sir but i am not pyrogram user
Check out my repo
https://github.com/jattpawan/evilbot
