### ISSUE TITLE
Add PyDub For Audio Manipulation Pypi

### ISSUE THREAD

**Issue by KyotoByte** [pytgcalls/pytgcalls#226]
**Feature Request: Add PyDub for Audio Manipulation Pypi**

**Problem:**  Currently FFMPEG Have Lack Of  Audio Processing Function 

**Solution:** Integrate PyDub, Python Library For Audio Manipulation, To Ehance Audio Processing Functionalities. PyDub Offers Tasks Like Cutting, Concatenating, And Applying Effects To Audio Files.

**Alternatives:** Currently We Can Use As Externally As Function

**Additional Context:** PyDub Pypi API Simplifies Complex Audio Operations, Ensuring User Experience For Processing Audio Files On PyTgCalls

**Comment by SantiiRepair** [comment]
@KyotoByte 🤪

**Comment by Laky-64** [comment]
Added the possibility to manipulate audio starting from 2.1.0

**Comment by KyotoByte** [comment]
Wonderful
