### ISSUE TITLE
The call user function doesn't work on Python 3.8 but works on 3.12

### ISSUE THREAD

**Issue by Dante4** [pytgcalls/pytgcalls#230]
**Describe the bug**
On Python 3.8 the call to user is stuck on Exchanging Encryption Keys
![image](https://github.com/pytgcalls/ntgcalls/assets/20700515/6cbce8c8-7d20-4402-aaaf-60f6da86a98f)
On Python 3.12 the call goes thought and start playing pre-recorded message
![image](https://github.com/pytgcalls/ntgcalls/assets/20700515/6bbe7b7d-a71f-4e24-a795-57f75be42cab)

**To Reproduce**
1. Clear ubuntu
pip3 install -U git+https://github.com/pytgcalls/pytgcalls@dev
pip3 install https://github.com/PyrogramMod/PyrogramMod/archive/refs/heads/main.zip
pip3 install TgCrypto
2. use https://github.com/pytgcalls/pytgcalls/blob/dev/example/piped_audio_calls/example_piped_audio.py
3. python3 ./example_piped_audio.py

**Expected behavior**
The call is working

**Environment**
 - OS: Ubuntu 22.04
 - Branch dev
 - Python Version 3.8.10
 - Python Version 3.12.2

**Additional context**
Also fails on both version if I add
@app.on_raw_update()
async def on_update(_, update, __, chats):
  print(update)
Logs:
Python 3.8 - https://pastebin.com/FLcRPs5U

Python 3.12 - https://pastebin.com/GyMNSSxM

**Comment by KSKOP69** [comment]
@Dante4 try with 3.10 or above

**Comment by chernyakoff** [comment]
if you try to start a p2p call every hour without changing anything in the code, then sometimes it will work
