### ISSUE TITLE
Workaround about client stuck in Exchanging Encryption Keys

### ISSUE THREAD

**Issue by Dante4** [pytgcalls/pytgcalls#232]
**Is your feature request related to a problem? Please describe.**
(Since right now we have problem with TG server side #231)
The problem is that when it (#231) happens the user stuck in "Exchanging Encryption Key" without any notification regarding will call ever establish or no. 
Also when userbot try to call such user there is no notification from pytgcall side regarding "busy user". In TG client you can see instant declined call.  
![image](https://github.com/pytgcalls/pytgcalls/assets/20700515/37525891-077a-4b34-a7e4-853fed95beb7)

**Describe the solution you'd like**
Add ability to interrupt the call if connection is going to fail (it's may be noticed most of the time by no-signaling information in logs)
or
Add ability to understand that client is busy and can't answer 

**Describe alternatives you've considered**
The messages parsing from userbot side, not pretty solution since when the user tire of waiting and click end call - you receive message that call was accepted.

**Comment by Laky-64** [comment]
Directly fixed ntgcalls connection starting from 1.2.2b1
