### ISSUE TITLE
The kicked event is not raised when the channel you are joined with is banned

### ISSUE THREAD

**Issue by Ishu-Hinata** [pytgcalls/pytgcalls#237]
**Describe the bug**
When Client has joined as channel in group calls, it's not getting updates when group call has ended or client as channel is kicked.

**To Reproduce**
1. Make client join group call as channel 
2. Use different account to end group call or kick client 
4. Client will not get updates, it works when client has joined as personal account 

**Expected behavior**
Client should be able to get updates when joined as channel 

**Log**
No error logs to this problem.

**Linux (please complete the following information):**
 - OS: [e.g. Linux Mint 20.1]
 - NodeJS Version [e.g. 1.14]
 - Python Version [e.g. 3.8.6]

**Additional context**

**Comment by Laky-64** [comment]
Do you have a little reproducible code?
And another question, the userbot should be the creator of the group to join as channel?
