### ISSUE TITLE
data type mismatch in the example_multiple.py file in the pytgcalls repository !

### ISSUE THREAD

**Issue by rezatg** [pytgcalls/pytgcalls#249]
Hello @Laky-64,
I encountered an issue in the `example_multiple.py` section of the pytgcalls Github repository.

You have passed the mtproto clients to the parameter clients here, while the value of that parameter is `List[PyTgCalls]` not `List[ClientMtproto]`.

You can find the code at this link: https://github.com/pytgcalls/pytgcalls/blob/4a67bb0d546c64af3f019724ceee8d1e11a3eda3/example/multiple_clients/example_multiple.py#L61 and also https://github.com/pytgcalls/pytgcalls/blob/4a67bb0d546c64af3f019724ceee8d1e11a3eda3/pytgcalls/methods/utilities/compose.py#L9)

Replace the code :
```python
compose([call_py, call_py2])
```

**Comment by Laky-64** [comment]
Fixed
