### ISSUE TITLE
How to get the parameters to raise hand in voice chat

### ISSUE THREAD

**Issue by githubuserpro69** [pytgcalls/pytgcalls#253]
How to get the parameters to raise hand in voice chat using this 

```py
await client(functions.phone.EditGroupCallParticipantRequest(call=..., participant=..., raise_hand=True))
```
Or is there any other simpler way to raise hand in voice chat

**Comment by Laky-64** [comment]
Just use:
https://pytgcalls.github.io/PyTgCalls/Advanced%20Methods/Get%20Participants

Returns a list of:
https://pytgcalls.github.io/PyTgCalls/Advanced%20Types/GroupCallParticipant
