### ISSUE TITLE
Sometimes raw file doesn't play

### ISSUE THREAD

**Issue by mojtabaasg** [pytgcalls/pytgcalls#44]
Sometimes after starting GroupCall, nothing happens, bot will stay mute, and after several seconds, bot will leave voicechat.
I have to execute my code several times to make it play my music.
raw file is ok and has no problems.
i think this is a bug in pytgcalls
thanks

**Comment by Laky-64** [comment]
Can you send to me the logs in ultra_verbose?

**Comment by Laky-64** [comment]
this question turns out to be inactive
