### ISSUE TITLE
Add Audio Recording support!

### ISSUE THREAD

**Issue by Laky-64** [pytgcalls/pytgcalls#81]
Add the possibility to record audio of voice chat

**Comment by iiiiii1wepfj** [comment]
video too

**Comment by Chicchi7393** [comment]
Is there gonna be a function for starting the recording?

**Comment by Laky-64** [comment]
Soon, is planned on https://github.com/pytgcalls/pytgcalls/projects/2

**Comment by Chicchi7393** [comment]
ok
