### ISSUE TITLE
High cpu consumption, any solution?

### ISSUE THREAD

**Issue by Laky-64** [pytgcalls/pytgcalls#9]
This following line cause the high cpu consumption, but if when is paused and the setTimeut is setted to every 500 ms not have cpu consumption problem

https://github.com/pytgcalls/pytgcalls/blob/master/src/stream.ts#L97-L133

**Comment by BlackStoneReborn** [comment]
I guess you can close this now..?

**Comment by Laky-64** [comment]
i want to reduce more the cpu consumption
